//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelsDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int ID { get; set; }
        public int BandID { get; set; }
        public int UserID { get; set; }
        public System.DateTime Sent { get; set; }
        public string Message { get; set; }
        public Nullable<bool> Result { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
    
        public virtual Band Band { get; set; }
        public virtual User User { get; set; }
    }
}
