//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelsDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BandUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BandUser()
        {
            this.Skills = new HashSet<Skill>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PermisionID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> BandID { get; set; }
    
        public virtual Band Band { get; set; }
        public virtual Permission Permission { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Skill> Skills { get; set; }
    }
}
