//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelsDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int ID { get; set; }
        public Nullable<int> BandID { get; set; }
        public Nullable<int> UserID { get; set; }
        public int TypeID { get; set; }
        public System.DateTime Sent { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
    
        public virtual Band Band { get; set; }
        public virtual NotificationType NotificationType { get; set; }
        public virtual User User { get; set; }
    }
}
